// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_download_fileName_ from "./routes/api/download/[fileName].ts";
import * as $api_format from "./routes/api/format.ts";
import * as $api_list_formats from "./routes/api/list-formats.ts";
import * as $api_version from "./routes/api/version.ts";
import * as $download from "./routes/download.tsx";
import * as $index from "./routes/index.tsx";
import * as $list_formats from "./routes/list-formats.tsx";
import * as $DownloadableFile from "./islands/DownloadableFile.tsx";
import * as $ListFormats from "./islands/ListFormats.tsx";
import * as $SearchForm from "./islands/SearchForm.tsx";
import * as $ToggleTheme from "./islands/ToggleTheme.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/api/download/[fileName].ts": $api_download_fileName_,
    "./routes/api/format.ts": $api_format,
    "./routes/api/list-formats.ts": $api_list_formats,
    "./routes/api/version.ts": $api_version,
    "./routes/download.tsx": $download,
    "./routes/index.tsx": $index,
    "./routes/list-formats.tsx": $list_formats,
  },
  islands: {
    "./islands/DownloadableFile.tsx": $DownloadableFile,
    "./islands/ListFormats.tsx": $ListFormats,
    "./islands/SearchForm.tsx": $SearchForm,
    "./islands/ToggleTheme.tsx": $ToggleTheme,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
